version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "54321:5432"
    volumes:
      - pgData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - internal_network

  backend:
    container_name: backend
    build: ./Practicas-Teclab
    ports:
      - "3000:3000"
    volumes:
      - ./Practicas-Teclab:/app
    environment:
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - internal_network

  frontend:
    container_name: frontend
    build: ./Practicas-Teclab/front/cabanias
    ports:
      - "5173:5173"
    volumes:
      - ./Practicas-Teclab/front/cabanias:/app
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend
    networks:
      - internal_network

volumes:
  pgData:
networks:
  internal_network:
    driver: bridge


